FROM docker.io/gentoo/stage3:latest
RUN emerge-webrsync -q
RUN emerge --sync -q
RUN echo 'FEATURES="${FEATURES} parallel-fetch parallel-install"' >> /etc/portage/make.conf
RUN echo 'MAKEOPTS="-j4 -l12"' >> /etc/portage/make.conf
RUN echo 'RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"' >> /etc/portage/make.conf
RUN echo 'EMERGE_DEFAULT_OPTS="-gq --binpkg-respect-use=y --jobs 4"' >> /etc/portage/make.conf
RUN echo 'EMERGE_RSYNC_OPTS="${EMERGE_RSYNC_OPTS} --no-motd"' >> /etc/portage/make.conf
RUN echo 'PORTAGE_RSYNC_OPTS="${PORTAGE_RSYNC_OPTS} --no-motd"' >> /etc/portage/make.conf
RUN emerge net-libs/nodejs dev-vcs/git dev-util/pkgcheck app-portage/gentoolkit
RUN eclean-pkg -d
RUN eclean-dist -df
