name: update builder image

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  update:
    runs-on: docker
    container:
      image: quay.io/podman/stable
      options: --privileged

    steps:
      - name: install git
        run: dnf install -y git

      - name: checkout
        run: |
          git clone --depth 1 https://codeberg.org/slashpotato/gentoo-overlay.git --depth 1 --recursive .

      - name: log into codeberg registry
        run: echo "${{ secrets.CODEBERG_TOKEN }}" | podman login codeberg.org -u "${{ secrets.CODEBERG_USER }}" --password-stdin

      - name: build base
        run: podman build --no-cache -t codeberg.org/slashpotato/overlay-builder:latest .

      - name: push
        run: podman push codeberg.org/slashpotato/overlay-builder:latest
