#!/usr/bin/env python3
"""
Патчит ебилд llvm-core/llvm из ::gentoo так, чтобы он умел собирать
BOLT как sibling-проект в том же дереве llvm-project (LLVM_ENABLE_PROJECTS=bolt),
под USE-флагом "bolt".

Использование:
    patch_llvm_bolt.py <path-to-upstream-ebuild> <path-to-output-ebuild>

Идемпотентен: если ебилд уже пропатчен, второй запуск ничего не ломает.
"""
import re
import sys
from pathlib import Path


def add_component(text: str) -> str:
	"""Добавляет 'bolt' в массив LLVM_COMPONENTS, если его там нет."""
	m = re.search(r"LLVM_COMPONENTS=\(([^)]*)\)", text, re.S)
	if not m:
		raise SystemExit("не нашёл LLVM_COMPONENTS=( ... ) в ебилде")

	items = m.group(1).split()
	if "bolt" in items:
		return text  # уже пропатчено

	items.append("bolt")
	new_array = "LLVM_COMPONENTS=( " + " ".join(items) + " )"
	return text[: m.start()] + new_array + text[m.end():]


def add_iuse(text: str) -> str:
	"""Добавляет 'bolt' в IUSE (в виде опционального +bolt), если его там нет."""
	m = re.search(r'^IUSE="([^"]*)"', text, re.M)
	if not m:
		raise SystemExit("не нашёл IUSE=\"...\" в ебилде")

	if re.search(r"(^|[\s+])bolt($|\s)", m.group(1)):
		return text  # уже есть

	new_iuse = f'IUSE="{m.group(1).rstrip()} bolt"'
	return text[: m.start()] + new_iuse + text[m.end():]


def add_cmake_arg(text: str) -> str:
	"""
	Добавляет в src_configure() строку с условным
	-DLLVM_ENABLE_PROJECTS=bolt, если такой строки ещё нет.
	Ищем mycmakeargs=( ... ) и вставляем перед закрывающей скобкой.
	"""
	if "LLVM_ENABLE_PROJECTS=bolt" in text:
		return text  # уже пропатчено

	m = re.search(r"(mycmakeargs=\(\n)(.*?)(\n\t\))", text, re.S)
	if not m:
		raise SystemExit("не нашёл mycmakeargs=( ... ) в src_configure()")

	insertion = '\t\t$(usex bolt -DLLVM_ENABLE_PROJECTS=bolt "")\n'
	patched = m.group(1) + m.group(2) + "\n" + insertion.rstrip("\n") + m.group(3)
	return text[: m.start()] + patched + text[m.end():]


def add_marker(text: str) -> str:
	"""Комментарий-маркер сверху файла, чтобы было видно, что это не ванильный ебилд."""
	marker = (
		"# ------------------------------------------------------------------\n"
		"# Patched by slashpotato/llvm-bolt-overlay: adds bolt to LLVM_COMPONENTS\n"
		"# and a conditional -DLLVM_ENABLE_PROJECTS=bolt behind USE=bolt.\n"
		"# Do not edit by hand — regenerated by .forgejo/workflows/sync-llvm-bolt.yml\n"
		"# ------------------------------------------------------------------\n"
	)
	if marker in text:
		return text
	# EAPI должна остаться первой значимой строкой ебилда, так что маркер после неё
	lines = text.splitlines(keepends=True)
	for i, line in enumerate(lines):
		if line.startswith("EAPI="):
			lines.insert(i + 1, "\n" + marker)
			break
	else:
		lines.insert(0, marker)
	return "".join(lines)


def main() -> None:
	if len(sys.argv) != 3:
		print(__doc__)
		sys.exit(1)

	src, dst = Path(sys.argv[1]), Path(sys.argv[2])
	text = src.read_text()

	text = add_component(text)
	text = add_iuse(text)
	text = add_cmake_arg(text)
	text = add_marker(text)

	dst.parent.mkdir(parents=True, exist_ok=True)
	dst.write_text(text)
	print(f"OK: {src} -> {dst}")


if __name__ == "__main__":
	main()
